title: "Ariel's personal website"
description: "The world in my eyes"
baseurl: ""
url: "https://ariel-sketch.github.io"

remote_theme: julianolf/jekyll-theme-8bit
plugins:
  - jekyll-remote-theme
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about/
  - title: "My Works"
    url: /works/
  - title: "Community Service"
    url: /community/
  - title: "Research"
    url: /research/
  - title: "Other"
    url: /other/
